# Define the name of the workflow.
name: E2E Tests

# Define the events that trigger the workflow.
on:
  # Run the workflow when a pull request is made to the "main" branch.
  pull_request:
    branches: [main]
  # Allow running the workflow manually from the GitHub Actions tab.
  workflow_dispatch:

# Define the jobs in this workflow.
jobs:
  e2e-tests:
    # Run this job on the latest Ubuntu (Linux) runner hosted by GitHub.
    runs-on: ubuntu-latest
    # Limit the execution time of this job to 15 minutes.
    timeout-minutes: 15
    # Define the steps in this job.
    steps:
      # Checkout the this repository.
      - name: Checkout
        uses: actions/checkout@v3

      # Build and start the "express-app" and "react-app" containers in detached mode to avoid blocking the workflow.
      - name: Start local environment with Docker Compose
        run: docker compose up -d

      # Build the Docker image for E2E tests.
      - name: Build E2E Docker image
        run: docker build -t playwright-tests ./e2e

      - name: Register pre-E2E container memory usage
        run: |
          # Iterate over all running containers and store their initial memory usage (obtained using docker stats) into GITHUB_ENV variables of the form of CONTAINER_NAME_INITIAL_MEMORY_USAGE, and log the results
          docker ps --format '{{.Names}}' | while read container; do
            initial_memory=$(docker stats --no-stream --format '{{.MemUsage}}' $container | awk -F '/' '{print $1}')
            echo "${container^^}_INITIAL_MEMORY_USAGE=$initial_memory" >> $GITHUB_ENV
          done

      # Execute the E2E tests
      - name: Run E2E tests against local environment
        run: docker run -v $(pwd)/e2e-report:/app/e2e-report --name playwright-tests --network=host playwright-tests yarn e2etest:ci

      - name: Register post-E2E container memory usage
        run: |
          # Iterate over all running containers and store their final memory usage (obtained using docker stats) into GITHUB_ENV variables of the form of CONTAINER_NAME_FINAL_MEMORY_USAGE, and log the results
          docker ps --format '{{.Names}}' | while read container; do
            final_memory=$(docker stats --no-stream --format '{{.MemUsage}}' $container | awk -F '/' '{print $1}')
            echo "${container^^}_FINAL_MEMORY_USAGE=$final_memory" >> $GITHUB_ENV
          done

      - name: Check for memory leaks
        run: |
          # Iterate over all running containers and check whether their final memory usage is ${{env.MEMORY_LEAK_PERCENTAGE_THRESHOLD}} greater than their initial memory usage, and log the results, and fail if threshold exceeded
          docker ps --format '{{.Names}}' | while read container; do
            initial_memory=$(echo ${{env.${container^^}_INITIAL_MEMORY_USAGE}} | awk -F '.' '{print $1}' | sed 's/[A-Za-z]*//g')
            final_memory=$(echo ${{env.${container^^}_FINAL_MEMORY_USAGE}} | awk -F '.' '{print $1}' | sed 's/[A-Za-z]*//g')
            memory_leak_percentage=$(( (final_memory - initial_memory) * 100 / initial_memory ))
            if [[ $memory_leak_percentage -gt ${{env.MEMORY_LEAK_PERCENTAGE_THRESHOLD}} ]]; then
              echo "Memory leak detected in $container: memory usage increased by $memory_leak_percentage%."
              exit 1
            else
              echo "No memory leak detected in $container."
            fi
          done
        env:
          MEMORY_LEAK_PERCENTAGE_THRESHOLD: 50

      # Prepare the logs for all containers.
      - name: Prepare container logs
        if: always() # Ensure logs are captured, even if the tests fail.
        run: |
          # Create the "logs" directory
          mkdir -p logs

          # Export each Docker container's logs to files in the "logs" directory.
          docker logs express-app >& logs/express-app.log
          docker logs react-app >& logs/react-app.log
          docker logs playwright-tests >& logs/playwright-tests.log

      # Upload the logs for all containers as an artifact.
      - name: Upload container logs
        if: always() # Ensure logs are captured, even if the tests fail.
        uses: actions/upload-artifact@v2
        with:
          name: E2E Logs
          path: logs

      # Upload the test report and video recordings as an artifact.
      - name: Upload Test Report
        if: always() # Ensure test report is captured, even if the tests fail.
        uses: actions/upload-artifact@v2
        with:
          name: E2E Test Report
          path: e2e-report
